pipeline
{
    agent {
  l   abel 'node1'
     }
    stages{
        stage('build'){
            steps{
                sh 'mvn clean package'
            }
            post{
                sucess {
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
    }
}