pipeline
{
    agent none
    stages{
        stage('build'){
            steps{
                echo "This is build Stage"
            }
        }
        stage('test'){
            steps{
                echo "This is test stage"
            }
        }
        stage('deploy'){
            steps{
                echo 'This is deploy stage'
            }
        }
    }
}