pipeline
{
tools{
    maven 'maven'
   

}
    agent {

    label 'node1'

     }
    stages{
        stage('build'){
            steps{
                sh 'mvn clean package'
            }
            post{
                success {
                    archiveArtifacts artifacts: 'home/ubuntu/jenkins/workspace/test-pipeline/target/*.war'
                }
            }
        }
    }
}
